#ifndef SHELLCONF_H
#define SHELLCONF_H

#define SHELL_CMD_TEST_ENABLED false
#define SHELL_CMD_EXIT_ENABLED false
#define SHELL_USE_HISTORY true
#define SHELL_MAX_LINE_LENGTH 32

#endif // SHELLCONF_H
